#!/bin/bash
echo $#
if [ $# -lt 1 ]; then
    echo 'Usage: dl <day> [<session>]'
    exit 1
fi
if [ $1 -gt 25 ]; then
    echo 'Invalid day'
    exit 1
fi
if [ $# -ge 2 ]; then
    SESSION=$2
else
    SESSION=`cat /Users/yarin/.config/aocd/token`
fi
curl https://adventofcode.com/2020/day/$1/input --cookie "session=$SESSION" > day$1.in

DAY=$1
if [ $DAY -lt 10 ]; then
    DAY=0$DAY
fi
cp day$1.in ~/.config/aocd/$SESSION/2020_${DAY}_input.txt
